services:
  api:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD","curl","-fsS","http://localhost:8000/health"]
      interval: 20s
      timeout: 4s
      retries: 6
      start_period: 15s

  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD","wget","-qO-","http://localhost:5173"]
      interval: 20s
      timeout: 4s
      retries: 6
      start_period: 10s
